### ISSUE TITLE
Table of Contents / page subnav display

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/papers#25] opened 2024-02-29 20:26 UTC
When a page has lots of children, it looks like this:

<img width="1233" alt="Screenshot 2024-02-29 at 15 20 31" src="https://github.com/omeka-s-themes/papers/assets/28012148/90975c05-e496-4e0c-b8c6-9e5f9d3cc074">

Which is also what the TOC block looks like:

<img width="1223" alt="Screenshot 2024-02-29 at 15 21 17" src="https://github.com/omeka-s-themes/papers/assets/28012148/1617cf9f-1486-4503-aca9-96294418f1ca">

I wonder if we can put all those entries on one line and squish them in a bit better?

I know that when you have a big tree of pages it will use that space, but flex should handle that, I think. 

<img width="1239" alt="Screenshot 2024-02-29 at 15 24 48" src="https://github.com/omeka-s-themes/papers/assets/28012148/5273775f-f330-4cbc-b994-2b92a776f79b">

**Comment by kimisgold** [comment] 2024-03-01 18:20
For context, [this is the website Papers was abstracted from](https://wardepartmentpapers.org/s/home/page/Guides). You can see how it's limited to the single level of top navigation, and then most of its page structure exists within the "Guides" section. The theme wasn't really built to hold deep levels of content because the emphasis is on the accompanying Scripto theme. I think it's also okay to have themes geared towards more minimal content. I'd be happy to provide more documentation speaking to this. I can improve the 3rd level of child pages in that third screenshot, but further than that, I'm a bit reticent to go deep into developing out more navigation support.

**Comment by allanaaa** [comment] 2024-03-01 20:01
If it doesn't work as a public theme for flexible uses, I don't see why we wouldn't change it to be more useful. 

It looks like you already have flex set up, you just need to modify the width setting:

<img width="1110" alt="Screenshot 2024-03-01 at 14 52 45" src="https://github.com/omeka-s-themes/papers/assets/28012148/3211f2e1-cc13-455d-bda0-576a5887232a">

Maybe the margins as well? 

<img width="1122" alt="Screenshot 2024-03-01 at 14 57 44" src="https://github.com/omeka-s-themes/papers/assets/28012148/104c8e89-2c46-49a0-9ecb-49aa866e61fa">

But if you think having a not-always-very-useful-theme is preferable, okay. Again, as long as we warn people about it before they get far into customizing and then find the limitations on their own.

**Comment by kimisgold** [comment] 2024-03-12 17:37
I've provided styling for the third level of navigation. I agree that we should document what the navigation styling currently supports, possibly providing context by providing examples in the original use case.

**Comment by allanaaa** [comment] 2024-03-12 20:38
I've just pulled but am not seeing any changes. Do you mean you only made changes in the TOC page block?

**Comment by kimisgold** [comment] 2024-03-12 20:45
Yes, these changes only affect the TOC page block. I believe the default subnavigation functionality only shows the immediate next level of navigation.

**Comment by allanaaa** [comment] 2024-04-08 15:25
I'm getting an odd word-wrap or line length on the lower level entries. 

<img width="1155" alt="Screenshot 2024-04-08 at 11 17 38" src="https://github.com/omeka-s-themes/papers/assets/28012148/224204af-289f-4606-bdf4-26eeb9caa1a7">

**Comment by kimisgold** [comment] 2024-04-08 20:25
I'm having trouble replicating this. Can you provide a live example?

**Comment by allanaaa** [comment] 2024-04-09 17:18
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/welcome

**Comment by kimisgold** [comment] 2024-04-09 18:23
Thanks, that helped a lot. It's something about the flex layout and how the widths of those child lists are being calculated. I set them to `width: 100%` and I think that fixes it.

**Comment by allanaaa** [comment] 2024-04-09 19:44
Yep, that's done it.

<img width="1262" alt="Screenshot 2024-04-09 at 15 10 49" src="https://github.com/omeka-s-themes/papers/assets/28012148/148ae484-1cba-4b5a-b4df-82cdcef54e6b">


I'll just put one more plug in for how I'd like it to look:

<img width="1258" alt="Screenshot 2024-04-09 at 14 46 02" src="https://github.com/omeka-s-themes/papers/assets/28012148/9b76fa3b-0209-46f0-8181-50062a6e2af2">

A better use of space; the content can all easily fit on one row for most uses. I just removed the width calculation on `li`s and took off the margins.

**Comment by kimisgold** [comment] 2024-06-12 17:00
Circling back to this, I think we're wading into preference over functional issues. Again, this theme is intended to be paired with a Scripto project. While it _can_ be used more generally, I'm fine with it and other themes being designed with more specific usage in mind. It seems that it's gotten to the point of displaying as intended, so I'm closing this.

**Closed as completed by kimisgold** 2024-06-12 17:00 UTC
